/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_wangzs_android_jnibase_JNIManager */

#ifndef _Included_com_wangzs_android_jnibase_JNIManager
#define _Included_com_wangzs_android_jnibase_JNIManager
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_wangzs_android_jnibase_JNIManager
 * Method:    testJni
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wangzs_android_jnibase_JNIManager_testJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
